Fix shellcheck lints

diff --git a/git-ff b/git-ff
--- a/git-ff
+++ b/git-ff
@@ -2,7 +2,7 @@
 
 # Inspired by https://stackoverflow.com/a/4157435/6936976
 
-if [[ "$(git rev-parse --is-inside-work-tree 2> /dev/null)" != "true" ]]; then
+if [ "$(git rev-parse --is-inside-work-tree 2> /dev/null)" != "true" ]; then
 	echo "fatal: not a git repository (or any of the parent directories): .git" >&2
 	exit 128
 fi
@@ -26,6 +26,10 @@ _die() {
 	exit "$1"
 }
 
+_shorthash() {
+	echo "$1" | cut -c1-7
+}
+
 #
 # _fastforward: do the actual fastforwarding
 #
@@ -43,11 +47,10 @@ _fastforward() {
 	refname="$1"
 	target_hash="$2"
 
-	base_hash=$(git show-ref -s --verify "$refname" 2> /dev/null)
-	echo "$base_hash"
-	if [ $? -ne 0 ]; then
+	if ! base_hash=$(git show-ref -s --verify "$refname" 2> /dev/null); then
 		return 4
 	fi
+	echo "$base_hash"
 
 	if [ "$base_hash" = "$target_hash" ]; then
 		return 5
@@ -123,98 +126,96 @@ if [ -n "$flag_all" ]; then
 		printf ' \e[34mskipped\e[0m: %s\n' "$1"
 	}
 
-	error=0
+	# error=0
 	git for-each-ref --shell --format='short=%(refname:short) ref=%(refname) upstream=%(upstream)' refs/heads |
-		while read -r branch; do
-			eval " $branch"
-			printf '\e[33m%s\e[0m:\n' "$short"
-			if [ -z "$upstream" ]; then
-				_skip "no tracking branch"
-				echo
-				continue
-			fi
-			target_hash=$(git show-ref -s --verify "$upstream")
-			if [ $? -ne 0 ]; then
-				echo " error: upstream doesn't point to anything"
-				error=1
-				echo
-				continue
-			fi
-
-			base_hash=$(_fastforward "$ref" "$target_hash")
-			case $? in
-				0) printf ' \e[32mfast-forwarded\e[0m: %s\n' "${base_hash:0:7}..${target_hash:0:7}"
-					git diff --stat "$base_hash" "$target_hash" --
-					;;
-				5) _skip "nothing to do"
-					;;
-
-				1) _skip "diverged"
-					;;
-				2) _skip "working tree is dirty"
-					;;
-				3) echo " error: update ref failed"
-					error=1
-					;;
-				4) echo " error: ref doesn't exist"
-					error=1
-					;;
-				*) echo " bug: unhandled return value from _fastforward"
-					error=1
-					;;
-			esac
-
+	while read -r branch; do
+		eval " $branch"
+		printf '\e[33m%s\e[0m:\n' "$short"
+		if [ -z "$upstream" ]; then
+			_skip "no tracking branch"
 			echo
-	done
+			continue
+		fi
+		if ! target_hash=$(git show-ref -s --verify "$upstream"); then
+			echo " error: upstream doesn't point to anything"
+			# error=1
+			echo
+			continue
+		fi
 
-	exit "$error"
+		base_hash=$(_fastforward "$ref" "$target_hash")
+		case $? in
+			0) printf ' \e[32mfast-forwarded\e[0m: %s\n' "$(_shorthash "$base_hash")..$(_shorthash "$target_hash")"
+				git diff --stat "$base_hash" "$target_hash" --
+				;;
+			5) _skip "nothing to do"
+				;;
+
+			1) _skip "diverged"
+				;;
+			2) _skip "working tree is dirty"
+				;;
+			3) echo " error: update ref failed"
+				# error=1
+				;;
+			4) echo " error: ref doesn't exist"
+				# error=1
+				;;
+			*) echo " bug: unhandled return value from _fastforward"
+				# error=1
+				;;
+		esac
+
+		echo
+	done
 else
 	if [ $# -ne 1 ] && [ $# -ne 2 ]; then
 		_usage
 	fi
 
+	if [ -n "$flag_fetch" ]; then
+		echo "error: --fetch not implemented for single branch fast-forward" >&2
+		exit 10
+	fi
+
 	# Get branch we're moving
 	ref="refs/heads/$1"
 	if ! git show-ref --quiet --verify "$ref"; then
-		_die 1 "error: branch '$1' not found"
+		_die 128 "error: branch '$1' not found"
 	fi
 
 	# Get target
 	target_hash=
 	if [ $# -lt 2 ]; then
-		target_hash=$(_get_upstream "$ref")
-		if [ $? -ne 0 ]; then
-			_die 1 "error: no tracking branch for '$1'"
+		if ! target_hash=$(_get_upstream "$ref"); then
+			_die 128 "error: no tracking branch for '$1'"
 		fi
 	else
 		# XXX what if there are multiple results
-		target_hash=$(git show-ref -s "$2" | head -n1)
-		if [ $? -ne 0 ]; then
-			_die 1 "error: '$2' is not a valid object"
+		if ! target_hash=$(git show-ref -s "$2" | head -n1); then
+			_die 128 "error: '$2' is not a valid object"
 		fi
 	fi
 
 	base_hash=$(_fastforward "$ref" "$target_hash")
 
 	case $? in
-		0) echo "fast-forwarding $1: ${base_hash:0:7}..${target_hash:0:7}"
+		0) echo "fast-forwarding $1: $(_shorthash "$base_hash")..$(_shorthash "$target_hash")"
 			git diff --stat "$base_hash" "$target_hash" --
 			;;
-		5) echo "fast-forwarding $1: ${base_hash:0:7}..${target_hash:0:7}"
+		5) echo "fast-forwarding $1: $(_shorthash "$base_hash")..$(_shorthash "$target_hash")"
 			echo "nothing to do"
 			;;
 
-		1) _die 2 "cannot fast-forward: diverging history"
+		1) _die 1 "cannot fast-forward: diverging history"
 			;;
-		2) exit 2
+		2) exit 1
 			;;
-		3) _die 3 "cannot fast-forward: git update-ref failed"
+		3) _die 2 "cannot fast-forward: git update-ref failed"
 			;;
-		4) _die 3 "cannot fast-forward: ref '$ref' doesn't exist"
+		4) _die 2 "cannot fast-forward: ref '$ref' doesn't exist"
 			;;
 		*) _die 10 "bug: unhandled return value from _fastforward"
 			;;
 	esac
-
-	exit 0
 fi
